name: PR on main

on:  
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    
    - name: Restore dependencies
      run: dotnet restore src\WebApp1.sln
    
    - name: Build
      run: dotnet build src\WebApp1.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test src\WebApp1.sln --no-build --verbosity normal --configuration Release
